export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const UNCOMPLETE_TASK = "UNCOMPLETE_TASK";
export const TOGGLE_COMPLETED = "TOGGLE_COMPLETED";
export const TOGGLE_UNCOMPLETED = "TOGGLE_UNCOMPLETED";
export const RESET_FILTERS = "RESET_FILTERS"; 